import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import Modal from '@/components/Modal/Modal'
import Calc from '@/components/Calc/Calc'
import { useState } from 'react'
import Slider from '@/components/Slider/Slider'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  function handleModalToggle() {
    setIsModalOpen(!isModalOpen);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Header handleModalToggle={handleModalToggle}/>
        <Slider handleModalToggle={handleModalToggle}/>
        <Calc handleModalToggle={handleModalToggle}/>
        <Modal isModalOpen={isModalOpen} handleModalToggle={handleModalToggle}/>
      </main>
    </>
  )
}
